version: "3.8"
services:
  app:
    container_name: uni-app
    build: .
    env_file:
      - .env
    volumes:
      - static_volume:/app/unilime/static
      - media_volume:/app/unilime/media
    depends_on:
      - db
    networks:
      - uni_net

  db:
    container_name: uni-db
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - $POSTGRES_PORT:5432
    networks:
      - uni_net

  nginx:
    container_name: uni-nginx
    image: nginx
    ports:
      - ${NGINX_PORT}:9311
    depends_on:
      - app
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - uni_net

  redis:
    container_name: uni-redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - uni_net
      
volumes:
  db_data:
  static_volume:
  media_volume:

networks:
  uni_net:
