name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[deploy]')
    steps:
      - name: Execute commands over ssh on production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SERVER_HOST}}
          username: ${{ secrets.PROD_SERVER_USERNAME}}
          key: ${{ secrets.PROD_SERVER_SSH_KEY}}
          script: |
            cd Unilime-Parser-API/
            git fetch
            git reset --hard origin/main
            docker compose up --build -d
